<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_on driving_icon icon-close-circle</name>
   <tag></tag>
   <elementGuidId>5511d502-9964-4f95-a305-2987184ba53b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.icon-close-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='custom_status__clear']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon-close-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SidebarContainer&quot;)/div[@id=&quot;lhsHeader&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;MenuWrapper status-dropdown-menu MenuWrapper--open&quot;]/div[@id=&quot;statusDropdownMenu&quot;]/ul[@class=&quot;Menu__content dropdown-menu&quot;]/li[@id=&quot;status-menu-custom-status&quot;]/button[@id=&quot;custom_status__clear&quot;]/i[@class=&quot;icon icon-close-circle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='custom_status__clear']/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
